spring:
  application:
    name: dgutforum
  rabbitmq:
    host: 192.168.80.131
    port: 6379
    name: itheima
    password: 123321
    virtual-host: dgutforum
    pool-size: 10
  datasource:
    datasource:
      druid:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.80.131:3306/dgutforum?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.dgutforum.article.entity


