server:
  port: 8008
spring:
  application:
    name: dgutforum
  rabbitmq:
    host: 192.168.80.131
    port: 5672
    name: itheima
    password: 123321
    virtual-host: dgutforum
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.80.131:3306/dgutforum?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123
  data:
    redis:
      host: 192.168.80.131
      port: 6379
      database: 0
      password: 123321


mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true


